import os

def main():
    """
    Removes user IDs from logs generated by db2pixellogs.py
    """
    for file in os.listdir('data'):
        with open('data/' + file, 'r') as src:
            with open('out/' + file, 'w') as dst:
                for line in src:
                    line = line.strip()
                    [date, user_id, username, x, y, color, action] = line.split('\t')
                    dst.write('\t'.join([date, username, x, y, color, action]) + '\n')

if __name__ == '__main__':
    main()
